from _typeshed import Incomplete

class SDCard:
    spi: Incomplete
    cs: Incomplete
    cmdbuf: Incomplete
    dummybuf: Incomplete
    tokenbuf: Incomplete
    dummybuf_memoryview: Incomplete
    def __init__(self, spi, cs) -> None: ...
    def init_spi(self, baudrate) -> None: ...
    sectors: Incomplete
    def init_card(self) -> None: ...
    cdv: int
    def init_card_v1(self) -> None: ...
    def init_card_v2(self) -> None: ...
    def cmd(self, cmd, arg, crc, final: int = 0, release: bool = True, skip1: bool = False): ...
    def readinto(self, buf) -> None: ...
    def write(self, token, buf) -> None: ...
    def write_token(self, token) -> None: ...
    def readblocks(self, block_num, buf) -> None: ...
    def writeblocks(self, block_num, buf) -> None: ...
    def ioctl(self, op, arg): ...
